// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsHAlCHMdV-1idgBVsmwu0tAx9SyiJBjo',
    appId: '1:488832465603:web:377f2e6c2701d9d7ce8076',
    messagingSenderId: '488832465603',
    projectId: 'poem-reciter',
    authDomain: 'poem-reciter.firebaseapp.com',
    storageBucket: 'poem-reciter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkp143PscibKosGwl0-ZiYirSdkAVjkmU',
    appId: '1:488832465603:android:2e29c3b2528c7c33ce8076',
    messagingSenderId: '488832465603',
    projectId: 'poem-reciter',
    storageBucket: 'poem-reciter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoBjFGAC29G68J1TQq5Y-j3lEd9opnmb4',
    appId: '1:488832465603:ios:beaab86507e58768ce8076',
    messagingSenderId: '488832465603',
    projectId: 'poem-reciter',
    storageBucket: 'poem-reciter.firebasestorage.app',
    iosBundleId: 'com.example.peomReciterApp',
  );

}